config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'pages/terms'
  get 'pages/updates'
  root to: 'pages#index'

  get 'about'   => 'pages#about'
  get 'help'    => 'pages#help'
  get 'pricing' => 'pages#pricing'
  get 'privacy' => 'pages#privacy'
  get 'terms'   => 'pages#terms'
  get 'updates' => 'pages#updates'

  get 'profile' => 'profile#show'

  resources :companies
  resources :jobs do
    collection do
      get 'search'
    end

    member do
      post 'filled'
      post 'vacant'
      post 'renew'
    end
  end

  devise_for :users, skip: %i[sessions registrations passwords]

  devise_scope :user do
    # sessions
    get    'login',  to: 'users/sessions#new', as: :new_user_session
    post   'login',  to: 'users/sessions#login', as: :user_session
    get    'sign_in', to: 'users/sessions#create', as: :start_user_session
    delete 'logout', to: 'users/sessions#destroy', as: :destroy_user_session

    # registrations
    put    '/account',  to: 'users/registrations#update'
    delete '/account',  to: 'users/registrations#destroy'
    post   '/account',  to: 'users/registrations#create'
    get    '/register', to: 'users/registrations#new',    as: :new_user_registration
    get    '/account',  to: 'users/registrations#edit',   as: :edit_user_registration
    patch  '/account',  to: 'users/registrations#update', as: :user_registration
    get    '/account/cancel', to: 'users/registrations#cancel', as: :cancel_user_registration

    # # passwords
    # get   'new-pass',  to: 'users/passwords#new',    as: :new_user_password
    # get   'edit-pass', to: 'users/passwords#edit',   as: :edit_user_password
    # patch 'edit-pass', to: 'users/passwords#update', as: :update_user_password
    # post  'new-pass',  to: 'users/passwords#create', as: :user_password
  end
end

app/models/job.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: jobs
#
#  id               :bigint(8)        not null, primary key
#  role             :string           not null
#  duration         :string
#  salary           :numrange         not null
#  requirements     :string           not null
#  qualification    :string           not null
#  perks            :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  archived         :boolean          default(FALSE)
#  remote_ok        :boolean          default(TRUE), not null
#  company_id       :bigint(8)        not null
#  city             :string           default(""), not null
#  country          :string           default(""), not null
#  apply_link       :text             default(""), not null
#  filled_at        :datetime
#  full_text_search :tsvector         not null
#

class Job < ApplicationRecord
  attr_accessor :salary_lower
  attr_accessor :salary_upper

  # This could be slightly overzealous, but that's because
  # I want to avoid any validation errors when someone sends
  # invalid input. We'll still go ahead and create the job
  # post with sensitized values.
  before_validation do
    l = salary_lower.to_f.abs
    u = salary_upper.to_f.abs
    self.salary = Range.new([l, u].min, [l, u].max)
  end

  belongs_to :company
  has_many   :renewals

  validates :company,       presence: true
  validates :duration,      presence: true
  validates :salary,        presence: true
  validates :requirements,  presence: true
  validates :qualification, presence: true
  validates :role,          presence: true

  def to_param
    "#{id}-#{role}-#{company.name}".parameterize
  end

  def title
    "#{role} at #{company.name}"
  end

  def compensation
    "USD #{salary.min.to_i} - #{salary.max.to_i}"
  end

  def published_on
    @published_on ||= renewals.order('renewed_on DESC').first&.renewed_on
  end

  def published?
    published_on.present?
  end

  def active?
    !archived && published? && (published_on + Job.validity_period.days) >= DateTime.now
  end

  # `Job.active` is a version of `all` that returns
  # jobs that haven't been archived and are still within
  # the validity period since they were posted.
  def self.all_active
    Job.find_by_sql <<~SQL
      WITH latest_renewals AS (
        SELECT job_id, max(renewed_on) AS published_on
          FROM renewals
      GROUP BY job_id
      )
      SELECT jobs.*
        FROM jobs
        JOIN latest_renewals ON latest_renewals.job_id = jobs.id
       WHERE NOT archived
             AND filled_at IS NULL
             AND tsrange(
               published_on,
               published_on + INTERVAL '#{validity_period}' DAY, '[]'
             ) @> now()::timestamp
      ORDER BY published_on DESC
    SQL
  end

  def self.validity_period
    (ENV['JOB_VALIDITY_PERIOD'] || 30).to_i.abs
  end

  def self.days_to_expiry
    (ENV['JOB_DAYS_TO_EXPIRY'] || 7).to_i.abs
  end

  def self.search(query)
    Job.find_by_sql [<<~SQL, query]
      WITH latest_renewals AS (
        SELECT job_id,
               max(renewed_on) AS published_on
          FROM renewals
      GROUP BY job_id
      )
      SELECT jobs.*
        FROM jobs
        JOIN latest_renewals ON latest_renewals.job_id = jobs.id
       WHERE NOT archived
             AND filled_at IS NULL
             AND tsrange(
              published_on,
              published_on + INTERVAL '#{validity_period}' DAY, '[]'
             ) @> now()::timestamp
             AND plainto_tsquery(?) @@ full_text_search
             ORDER BY created_at DESC
    SQL
  end

  def self.expires_soon
    Job.find_by_sql <<~SQL
      WITH latest_renewals AS (
        SELECT job_id,
               max(renewed_on) AS published_on
          FROM renewals
      GROUP BY job_id
      )
      SELECT jobs.*
        FROM jobs
        JOIN latest_renewals ON latest_renewals.job_id = jobs.id
       WHERE NOT archived
             AND filled_at IS NULL
             AND extract(days from now() - published_on) = #{validity_period - days_to_expiry}
    SQL
  end

  def self.expired_today
    Job.find_by_sql <<~SQL
      WITH latest_renewals AS (
        SELECT job_id,
               max(renewed_on) AS published_on
          FROM renewals
      GROUP BY job_id
      )
      SELECT jobs.*
        FROM jobs
        JOIN latest_renewals ON latest_renewals.job_id = jobs.id
      WHERE NOT archived
            AND filled_at IS NULL
            AND extract(days from now() - published_on) = #{validity_period}
    SQL
  end
end

app/controllers/jobs_controller.rb
# frozen_string_literal: true

class JobsController < ApplicationController
  before_action :set_job,            except: %i[new index create]
  before_action :authenticate_user!, except: %i[index show search renew]
  before_action :require_ownership, only: %i[edit update destroy renew]

  def index
    @jobs = Job.all_active
  end

  def new
    @current_user = current_user
    if @current_user.companies.empty?
      redirect_to new_company_path, notice: 'Register company first'
      return
    end
    @job = Job.new
  end

  def create
    company = current_user.companies.find_by(id: job_params[:company_id])
    raise_not_found unless company

    @job = company.jobs.build(job_params)
    if @job.save
      @job.renewals.create(job: @job, renewed_on: @job.created_at)
      redirect_to @job
      job_post_successful
    else
      render :new, status: :bad_request
    end
  end

  def show
    raise_not_found if @job.archived?
  end

  def edit; end

  def update
    if @job.update(edit_job_params)
      redirect_to @job, notice: 'Job has been updated.'
    else
      render :edit
    end
  end

  def filled
    @job.update_attribute(:filled_at, DateTime.now)
    redirect_to @job
  end

  def vacant
    @job.update_attribute(:filled_at, nil)
    redirect_to @job
  end

  def renew
    # only expired jobs can be renewed. if a job hasn't
    # expired, any attempt to renew should be ignored.
    unless @job.active?
      @job.renewals.create(renewed_on: DateTime.now)
      JobsMailer.with(job: @job).renewed.deliver_later
    end

    redirect_to @job
  end

  def search
    @matches = Job.search(params[:q])
    respond_to do |format|
      format.html
      format.json
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def require_ownership
    unless current_user&.companies&.include?(@job.company)
      redirect_to @job, notice: 'You are not authorized to edit this job post.'
    end
  end

  def set_company
    @company = current_user.companies.find_by(id: params[:job][:company_id])
    raise_not_found unless @company
  end

  def set_job
    @job = Job.find_by(id: params[:id])
    raise_not_found unless @job
  end

  def job_params
    params.require(:job).permit(
      :role,
      :duration,
      :salary_lower,
      :salary_upper,
      :requirements,
      :qualification,
      :perks,
      :company_id,
      :remote_ok,
      :city,
      :country,
      :apply_link
    )
  end

  def edit_job_params
    params.require(:job).permit(
      :role,
      :duration,
      :requirements,
      :qualification,
      :salary_lower,
      :salary_upper,
      :perks,
      :remote_ok,
      :city,
      :country,
      :apply_link
    )
  end

  def raise_not_found
    raise ActionController::RoutingError, 'not found'
  end

  def job_post_successful
    JobsMailer.with(job: @job).published.deliver_later
    # FIXME: use a job for this
    $tweetJob.update("New Job Vacancy: #{@job.title}. Read more at #{url_for(@job)}") if Rails.env.production?
  end
end

app/helpers/jobs_helper.rb
module JobsHelper

    def tweetButtonText
        return "https://twitter.com/intent/tweet?text=" + @job.company.name + " is looking for a " + @job.role + ". Read more on DevCongress Jobs, " + job_url + (" &hash;devcongressjobs &hash;hiring via @DevCongress").html_safe
    end

    def fbButtonText
        return "https://www.facebook.com/sharer.php?u=" + job_url
    end

end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true, :html => {:class => 'uk-form-stacked'}) do |form| %>
  <% if job.errors.any? %>
    <div class="error_explanation">
      <h2>
        <%= pluralize(job.errors.count, "error") %>
        prohibited this job from being saved:
      </h2>
      <ul>
        <% job.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="uk-margin">
    <h4><%= form.label :role, :class => "uk-form-label" %></h4>
    <p class="uk-text-small uk-text-muted">What will be their title at the new role?</p>
    <%= form.text_field :role, :class => "uk-input uk-width-1-2" %>
  </div>

  <div class="uk-margin">
    <h4><%= form.label :company_id, "Company Name", :class => "uk-form-label" %></h4>
    <%= form.collection_select(:company_id, @current_user.companies, :id, :name, {}, :class => "uk-select") %>
  </div>

  <div class="uk-margin">
    <%= form.check_box :remote_ok, :class => "uk-checkbox" %> Remote OK
  </div>

  <div class="uk-margin">
    <h4><%= form.label :duration, :class => "uk-form-label" %></h4>
    <%= form.select :duration, {"Full-time" => "Full-Time", "Part-time" => "Part-Time", "Contract" => "Contract", "Internship" => "Internship"}, {}, class: "uk-select" %>
    <p class="pure-form-message">What is the duration for this project?</p>
  </div>

  <div class="uk-margin">
    <h4><%= form.label :enagagement_type, :class => "uk-form-label" %></h4>
    <%= form.select :duration, {"Full-time" => "Full-Time", "Part-time" => "Part-Time", "Gig" => "Gig"}, {}, class: "uk-select" %>
    <p class="pure-form-message">What is the enagagement type for this project?</p>
  </div>

  <div class="uk-margin">
    <h4><%= form.label "Salary per month/project", :class => "uk-form-label" %></h4>
    Between <%= form.number_field :salary_lower, min: 0, class: "uk-input" %> and <%= form.number_field :salary_upper, min: 0, class: "uk-input" %>
    <p class="pure-form-message">Please note: there's a correlation between experience/expertise and compensation. Therefore, it's important to provide a figure to attract the right pool of candidates.</p>
  </div>

  <div class="uk-margin">
    <h4><%= form.label :requirements, :class => "uk-form-label" %></h4>
    <%= form.hidden_field :requirements, id: 'requirements' %>
    <trix-editor input="requirements"></trix-editor>
    <p class="pure-form-message">What are the 1 to 3 main things you need your future developer to help with? Please feel free to keep this as simple as possible and use every day language. Please be as specific as possible. For example: "I need the developer to help us build a new iPhone app"</p>
  </div>

  <div class="uk-margin">
    <h4><%= form.label :qualification, :class => "uk-form-label" %></h4>
    <%= form.hidden_field :qualification, id: 'qualification' %>
    <trix-editor input="qualification"></trix-editor>
    <p class="pure-form-message">This could be anything from "I require the developer to be fluent in French" to something as technical as "I require the developer to have an expert-level familiarity with PHP"</p>
  </div>

  <div class="uk-margin">
    <h4><%= form.label :perks, :class => "uk-form-label" %></h4>
    <%= form.hidden_field :perks, id: 'perks' %>
    <trix-editor input="perks"></trix-editor>
    <p class="pure-form-message">Please remember that the best developers are motivated by a mission. Please *sell* the project succinctly.</p>
  </div>

  <div class="uk-margin">
    <h4><%= form.label :contact_email, :class => "uk-form-label" %></h4>
    <%= form.email_field :contact_email, :class => "uk-input uk-width-1-2" %>
  </div>

  <div class="uk-margin">
    <h4><%= form.label :city, :class => "uk-form-label" %></h4>
    <%= form.text_field :city, :class => "uk-input uk-width-1-2" %>
  </div>

  <div class="uk-margin">
    <h4><%= form.label :country, :class => "uk-form-label" %></h4>
    <%= form.text_field :country, :class => "uk-input uk-width-1-2" %>
  </div>

  <div class="uk-margin">
    <h4><%= form.label :apply_link, "Link to Apply", :class => "uk-form-label" %></h4>
    <%= form.url_field :apply_link, :class => "uk-input uk-width-1-2" %>
  </div>

  <div class="uk-margin">
    <%= form.submit "Create Job", :class => "uk-button uk-button-primary" %>
  </div>
<% end %>

app/views/jobs/_jobs-list.html.haml
%ul.job--list
    - @jobs.each do |job|
        %li.job--list__item
            = link_to job.role + " at " + job.company, job, :class => "job--list__item-link"
            .job--list__action-group
                - if user_signed_in? && job.user_id == current_user.id
                    - if job.is_archived?
                        -# = link_to 'Unarchive', archive_path(job), :class => "job--list__action job--list__action-unarchive", method: :patch
                    - else
                        -# = link_to 'Archive', archive_path(job), :class => "job--list__action job--list__action-archive", method: :patch
                        -# = button_to 'Arch', archive_job_path, @job
                    = link_to 'Edit', edit_job_path(job), :class => "job--list__action job--list__action-edit"
                

app/views/jobs/_list.html.erb
<ul class="job--list dc-content-container">
    <% @jobs.each do |job| %>
        <li class="job--list__item">
        <%= link_to job, :class => "job--list__item-link" do %>
            <span class="job--list__item-role"><%= job.role %></span>
            <span class="job--list__item-company"><%= job.company.name %></span>
            <span class="job--list__item-type"><%= job.duration %></span>
            <span class="job--list__item-time"><%= time_ago_in_words(job.published_on) %> ago</span>
        <% end %>
        </li>
    <% end %>
</ul>

app/views/jobs/edit.html.erb
<% content_for :title do %>
  <%= " Edit Job - #{@job.role} at #{@job.company.name} | #{t('app.name')}" %>
<% end %>
<h1 class="page--title">Editing Job</h1>
<div class="page--legend-buttons">
  <p class="page--legend">
    <%= @job.role + " at " + @job.company.name %>
  </p>
</div>
<div class="main--content">
<%= form_with(model: @job, local: true, :class => "pure-form pure-form-stacked") do |form| %>
  <% if @job.errors.any? %>
    <div class="error_explanation">
      <h2>
        <%= pluralize(job.errors.count, "error") %>
        prohibited this job from being saved:
      </h2>
      <ul>
        <% @job.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :role %>
    <%= form.text_field :role %>
    <span class="pure-form-message">What will be their title at the new role?</span>
  </div>
  <div class="field">
    <%= form.check_box :remote_ok %> Remote OK
  </div>
  <div class="field">
    <%= form.label :duration %>
    <%= form.select(:duration, {"Full-time" => "Full-Time", "Part-time" => "Part-Time", "Contract" => "Contract", "Internship" => "Internship"}) %>
    <span class="pure-form-message">What is the duration for this project?</span>
  </div>
  <div class="field">
    <%= form.label "Salary per month/project" %>
    Between <%= form.number_field :salary_lower, min: 0 %> and <%= form.number_field :salary_upper, min: 0 %>
    <span class="pure-form-message">Please note: there's a correlation between experience/expertise and compensation. Therefore, it's important to provide a figure to attract the right pool of candidates.</span>
  </div>
  <div class="field">
    <%= form.label :requirements %>
    <%= form.text_area :requirements %>
    <span class="pure-form-message">What are the 1 to 3 main things you need your future developer to help with? Please feel free to keep this as simple as possible and use every day language. Please be as specific as possible. For example: "I need the developer to help us build a new iPhone app"</span>
  </div>
  <div class="field">
    <%= form.label :qualification %>
    <%= form.text_area :qualification %>
    <span class="pure-form-message">This could be anything from "I require the developer to be fluent in French" to something as technical as "I require the developer to have an expert-level familiarity with PHP"</span>
  </div>
  <div class="field">
    <%= form.label :perks %>
    <%= form.text_area :perks %>
    <span class="pure-form-message">Please remember that the best developers are motivated by a mission. Please *sell* the project succinctly.</span>
  </div>
  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>
  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>
  <div class="field">
    <%= form.label :apply_link, "Link to Apply" %>
    <%= form.url_field :apply_link %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Show', @job %>
|
<%= link_to 'Back', jobs_path %>
</div>

app/views/jobs/index.html.erb
<% content_for :title do %>
  <%= "All Jobs | #{t('app.name')}" %>
<% end %>

<main class="dc-jobs">
  <article>
    <section class="dc-page--header">
      <div class="uk-container">
        <h1 class="page--title">All Jobs</h1>
      </div>
    </section>

    <section class="dc-main--content">
      <div class="uk-container">
        <% if @jobs.empty? %>
          <ul class="job--list dc-content-container">
            <li class="job--list__item">No jobs are currently available</li>
          </ul>
        <% else %>
          <%= render 'list' %>
        <% end %>
      </div>
    </section>
  </article>
</main>

app/views/jobs/myjobs.html.erb
<% content_for :title do %>
  <%= "My Jobs | #{t('app.name')}" %>
<% end %>
<h1 class="page--title">All My Jobs</h1>
<div class="page--legend-buttons">
  <p class="page--legend">Jobs you have listed are here. Archived jobs are hidden from public view, and have a cream background.</p>
</div>
<div class="main--content">
  <% if @jobs.empty? %>
    <p>You have no jobs listed yet. 🤔</p>
    <% # %p Once a post has been created, you will not be able to delete it. Instead, you will be able to unhide it from public view. This is .  %>
    <%= link_to 'List your first Job', new_job_path %>
  <% else %>
    <%= render 'jobs/my-jobs-list' %>
  <% end %>
</div>
<br/>

app/views/jobs/new.html.erb
<% content_for :title do %>
  <%= "Add New Job | #{t('app.name')}" %>
<% end %>
<main class="dc-companies-new">
  <article>
    <section class="dc-page--header">
      <div class="uk-container">
        <div class="uk-grid">
          <div class="uk-width-1-2@m uk-margin-small-bottom">
            <h1 class="page--title">Add New Job</h1>
          </div>
          <div class="uk-width-1-2@m">
            <p class="dc-job-meta uk-text-right uk-text-middle"></p>
          </div>
        </div>
      </div>
    </section>

    <section class="dc-main--content">
      <div class="uk-container">
        <div class="uk-grid" >
          <div class="uk-flex-last uk-flex-first@m uk-width-expand@m">
            <div class="uk-card uk-card-default uk-card-body dc-content-container">
              <% if user_signed_in? %>
                <%= render 'form', job: @job, companies: @companies %>
                <%= link_to 'Back', jobs_path %>
              <% else %>
                <p>Please sign in to create a job listing</p>
                <%= link_to('Sign in', new_user_session_path) %>
                <p>or</p>
                <%= link_to('Sign up', new_user_registration_path) %>
              <% end %>
            </div>
          </div>

          <div class="uk-flex-first uk-flex-last@m uk-text-left uk-width-1-4@m">
            <div class="uk-card uk-card-default uk-card-body uk-margin-bottom dc-content-container">
              <h3>Instructions</h3>
              <p>Provide candid, relevant information for best results.</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  </article>
</main>

app/views/jobs/search.html.erb
<% content_for :title do %>
  <%= "Search Results | #{t('app.name')} " %>
<% end %>
<h1 class="page--title">Search Results for <%= params[:q] %></h1>
<% if @matches.empty? %>
  <h3>No results for the search term you entered.</h3>
  <p>Return to <%= link_to('all Jobs', jobs_path)%> or <%= link_to('create a new job', new_job_path)%></p>
<% else %>
  <h3><%= pluralize(@matches.length, 'match') %> were found:</h3>
  <ul>
    <% @matches.each do |match| %>
      <li>
        <h4><%= link_to match.title, job_url(match) %></h4>
        <p>
        <!--
          TODO: Right now we display the requirements of the job
          but we should replace this with the part of the job post
          that matched the user's query. And if possible highlight
          the matched words or phrases.
        -->
          <%= match.requirements %>
        </p>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/jobs/show.html.erb
<% content_for :title do %>
  <%= "#{@job.role} at #{@job.company.name} | #{t('app.name')}" %>
<% end %>

<main class="dc-home">
  <article>
    <section class="dc-page--header">
      <div class="uk-container">
        <div class="uk-grid">
          <div class="uk-width-1-2@m uk-margin-small-bottom">
            <h1 class="page--title"><%= @job.title %> <%= "(Inactive)" unless @job.active? %></h1>
          </div>
          <div class="uk-width-1-2@m">
            <p class="dc-job-meta uk-text-right@m">
              <span class="dc-job-type uk-margin-right"><%= @job.duration %></span>
              <% if @job.published? %>
              Posted <%= time_ago_in_words(@job.published_on) %> ago
              <% end %>
            </p>
          </div>
        </div>
      </div>
    </section>

    <section class="dc-main--content">
      <div class="uk-container">
        <div class="uk-grid" >
          <div class="uk-width-expand@m uk-margin-bottom">
            <div class="uk-card uk-card-default uk-card-body dc-content-container">
              <% unless @job.active? %>
                <h3 style="color: red">This job is not active!</h3>
              <% end %>
              <h3>About role</h3>
              <%= simple_format @job.requirements.to_s.html_safe %>

              <h3>Qualifications</h3>
              <%= simple_format @job.qualification.to_s.html_safe %>

              <h3>Perks</h3>
              <%= simple_format @job.perks.to_s.html_safe %>
            </div>
          </div>

          <div class="uk-text-center uk-width-1-3@m">
            <div class="uk-card uk-card-default uk-card-body uk-margin-bottom dc-content-container">
              <h2><%= link_to @job.company.name.capitalize, @job.company %></h2>
              <hr>
              <%= link_to('Tweet', tweetButtonText, :target => "_blank", :class => "share--button share--buttons__tweet", "data-hashtags" => "devcongressjobs", "data-related" => "DevCongress") %>	
              <%= link_to('Share', fbButtonText, :target => "_blank", :class => "share--button share--buttons__fb", "data-hashtags" => "devcongressjobs", "data-related" => "DevCongress") %>	

              <hr>

              <%= mail_to @job.company.email, @job.company.email, class: "uk-button uk-button-primary", style: "width: 100%" %>
            </div>

            <div class="uk-card uk-card-default uk-card-body dc-content-container">
              <p><strong>Salary</strong> <%= @job.compensation %> <strong><%= @job.remote_ok ? "Remote OK" : "No Remote" %></strong></p>
            </div>
          </div>
        </div>
      </div>
    </section>
  </article>
</main>