config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'pages/terms'
  get 'pages/updates'
  root to: 'pages#index'

  get 'about'   => 'pages#about'
  get 'help'    => 'pages#help'
  get 'pricing' => 'pages#pricing'
  get 'privacy' => 'pages#privacy'
  get 'terms'   => 'pages#terms'
  get 'updates' => 'pages#updates'

  get 'profile' => 'profile#show'

  resources :companies
  resources :jobs do
    collection do
      get 'search'
    end

    member do
      post 'filled'
      post 'vacant'
      post 'renew'
    end
  end

  devise_for :users, skip: %i[sessions registrations passwords]

  devise_scope :user do
    # sessions
    get    'login',  to: 'users/sessions#new', as: :new_user_session
    post   'login',  to: 'users/sessions#login', as: :user_session
    get    'sign_in', to: 'users/sessions#create', as: :start_user_session
    delete 'logout', to: 'users/sessions#destroy', as: :destroy_user_session

    # registrations
    put    '/account',  to: 'users/registrations#update'
    delete '/account',  to: 'users/registrations#destroy'
    post   '/account',  to: 'users/registrations#create'
    get    '/register', to: 'users/registrations#new',    as: :new_user_registration
    get    '/account',  to: 'users/registrations#edit',   as: :edit_user_registration
    patch  '/account',  to: 'users/registrations#update', as: :user_registration
    get    '/account/cancel', to: 'users/registrations#cancel', as: :cancel_user_registration

    # # passwords
    # get   'new-pass',  to: 'users/passwords#new',    as: :new_user_password
    # get   'edit-pass', to: 'users/passwords#edit',   as: :edit_user_password
    # patch 'edit-pass', to: 'users/passwords#update', as: :update_user_password
    # post  'new-pass',  to: 'users/passwords#create', as: :user_password
  end
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id              :bigint(8)        not null, primary key
#  name            :text             not null
#  industry        :text             not null
#  logo            :text             default(""), not null
#  website         :text             default(""), not null
#  description     :text             not null
#  email           :text             not null
#  phone           :text             not null
#  city            :text             not null
#  state_or_region :text             not null
#  post_code       :text             not null
#  country         :text             not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Company < ApplicationRecord
  # Associations
  has_many :jobs
  has_many :clients
  has_many :users, through: :clients

  # Validations
  validates :name,            presence: true
  validates :industry,        presence: true
  validates :website,         presence: true
  validates :description,     presence: true
  validates :email,           presence: true, uniqueness: true
  validates :phone,           presence: true
  validates :city,            presence: true
  validates :state_or_region, presence: true
  validates :post_code,       presence: true
  validates :country,         presence: true

  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company,          only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]
  before_action :require_ownership!,   only: [:edit, :update]

  def new
    @company = current_user.companies.build
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      current_user.companies << @company
      redirect_to @company
    else
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
    if @company.update_attributes(company_params)
      redirect_to @company
    else
      render :edit
    end
  end

  private

    def set_company
      @company = Company.find_by(id: params[:id])
      raise_not_found unless @company
    end

    def raise_not_found
      raise ActionController::RoutingError.new("not found")
    end

    def require_ownership!
      head(:forbidden) unless current_user.companies.include?(@company)
    end

    def company_params
      params.require(:company).permit(
        :name,
        :industry,
        :website,
        :description,
        :email,
        :phone,
        :city,
        :state_or_region,
        :post_code,
        :country,
        :logo
      )
    end
end

app/views/companies/_company_jobs_list.html.erb
<ul class="job--list">
  <% @company.jobs.each do |job| %>
    <% if job.active? %>
      <li class="job--list__item <%= job.filled_at? ? "filled" : "vacant" %>">
        <div class="job--list__item-link">
          <span class="job--list__item-role"><%= link_to job.role, job %></span>
          <span class="job--list__item-company">posted <%= time_ago_in_words(job.published_on) %> ago<%= ", filled" if job.filled_at? %></span>

          <div class="job--list__action-group">
            <% if current_user && current_user.companies.include?(@company) %>
              <%= button_to "Mark as Filled", filled_job_path(job), data: { confirm: "Are you sure?"}, :class => "job--list__item-type uk-button uk-button-primary uk-button-small" unless job.filled_at? %>
              <%= button_to "Mark as Vacant", vacant_job_path(job), :class => "job--list__item-type uk-button uk-button-primary uk-button-small" if job.filled_at? %>
            <% end %>
          </div>
        </div>
      </li>
    <% else %>
      <li class="job--list__item">
        <s>
          <%= link_to job.role, job, :class => "job--list__item-link" %>
          <% if job.published? %>
          <small>(posted <%= time_ago_in_words(job.published_on) %> ago)</small>
          <% end %>
        </s>
        <div class="job--list__action-group">
          <% if current_user && current_user.companies.include?(@company) %>
            <%= button_to "Publish", renew_job_path(job), :class => "job--list__action job--list__action-edit" %>
          <% end %>
        </div>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/companies/edit.html.erb
<% content_for :title do %>
  <%= "Update #{@company.name} | #{t('app.name')}" %>
<% end %>
<main class="dc-companies-new">
  <article>
    <section class="dc-page--header">
      <div class="uk-container">
        <div class="uk-grid">
          <div class="uk-width-1-2@m uk-margin-small-bottom">
            <h1 class="page--title">Update <%= @company.name %></h1>
          </div>
          <div class="uk-width-1-2@m">
            <p class="dc-job-meta uk-text-right uk-text-middle"></p>
          </div>
        </div>
      </div>
    </section>

    <section class="dc-main--content">
      <div class="uk-container">
        <div class="uk-grid" >
          <div class="uk-flex-last uk-flex-first@m uk-width-expand@m">
            <div class="uk-card uk-card-default uk-card-body dc-content-container">

              <%= form_with(model: @company, :class => "uk-form-horizontal") do |f| %>
                <div class="uk-margin">
                  <%= f.label :name, :class => "uk-form-label" %>
                  <div class="uk-form-controls">
                    <%= f.text_field :name, required: true, placeholder: "Acme Widgets Inc.", :class => "uk-input" %>
                  </div>
                </div>

                <div class="uk-margin">
                  <%= f.label :industry, "Industry" %>
                  <div class="uk-form-controls">
                    <%= f.select :industry, StaticData[:industries].map {|v| [v, v]}, {}, { class: "uk-select" } %>
                  </div>
                </div>

                <div class="uk-margin">
                  <%= f.label :description, "About", :class => "uk-form-label" %>
                  <%= f.hidden_field :description, required: true, id: 'description' %>
                  <div class="uk-form-controls">
                    <trix-editor input="description"></trix-editor>
                  </div>
                </div>

                <div class="uk-margin">
                  <%= f.label :website, "Website", :class => "uk-form-label" %>
                  <div class="uk-form-controls">
                    <%= f.url_field :website, :class => "uk-input" %>
                  </div>
                </div>

                <div class="uk-margin">
                  <%= f.label :email, "Contact Email", :class => "uk-form-label" %>
                  <div class="uk-form-controls">
                    <%= f.email_field :email, required: true, :class => "uk-input" %>
                  </div>
                </div>

                <div class="uk-margin">
                  <%= f.label :phone, "Contact Phone", :class => "uk-form-label" %>
                  <div class="uk-form-controls">
                    <%= f.telephone_field :phone, required: true, :class => "uk-input" %>
                  </div>
                </div>

                <div class="uk-margin">
                  <%= f.label :city, "City", :class => "uk-form-label" %>
                  <div class="uk-form-controls">
                    <%= f.text_field :city, require: true, :class => "uk-input" %>
                  </div>
                </div>

                <div class="uk-margin">
                  <%= f.label :state_or_region, "State/Region", :class => "uk-form-label" %>
                  <div class="uk-form-controls">
                    <%= f.text_field :state_or_region, require: true, :class => "uk-input" %>
                  </div>
                </div>

                <div class="uk-margin">
                  <%= f.label :post_code, "Post/Zip Code", :class => "uk-form-label" %>
                  <div class="uk-form-controls">
                    <%= f.text_field :post_code, require: true, :class => "uk-input" %>
                  </div>
                </div>

                <div class="uk-margin">
                  <%= f.label :country, "Country", :class => "uk-form-label" %>
                  <div class="uk-form-controls">
                    <%= f.select :country, StaticData[:countries].map {|v| [v[:name], v[:code]]}, {}, { class: "uk-select" } %>
                  </div>
                </div>
                
                <div class="uk-form-controls uk-padding-small uk-padding-remove-left">
                  <div class="uk-margin">
                    <%= f.submit "Save", :class => "uk-button uk-button-primary" %>
                    <%= link_to "Cancel", @company, :class => "uk-margin-left uk-padding-small" %>
                  </div>
                </div>
              <% end %>
            
            </div>
          </div>

          <div class="uk-flex-first uk-flex-last@m uk-text-left@m uk-width-1-4@m">
            <div class="uk-card uk-card-default uk-card-body uk-margin-bottom dc-content-container">
              <h3>Instructions</h3>
              <p>You're about to change information about your company.</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  </article>
</main>

app/views/companies/new.html.erb
<% content_for :title do %>
  <%= "Register Your Company | #{t('app.name')}" %>
<% end %>
<main class="dc-companies-new">
  <article>
    <section class="dc-page--header">
      <div class="uk-container">
        <div class="uk-grid">
          <div class="uk-width-2-3@l">
            <h1 class="page--title">Register Your Company</h1>
          </div>
          <div class="uk-width-1-3@l">
            <p class="dc-job-meta uk-text-right uk-text-middle"></p>
          </div>
        </div>
      </div>
    </section>

    <section class="dc-main--content">
      <div class="uk-container">
        <div class="uk-grid" >
          <div class="uk-flex-last uk-flex-first@m uk-width-expand@m">
            <div class="uk-card uk-card-default uk-card-body dc-content-container">
              <%= form_with(model: @company, :class => "uk-form-horizontal") do |form| %>
                <div class="uk-margin">
                  <%= form.label :name, :class => "uk-form-label" %>
                  <div class="uk-form-controls">
                    <%= form.text_field :name, required: true, placeholder: "Acme Widgets Inc.", :class => "uk-input" %>
                  </div>
                </div>

                <div class="uk-margin">
                  <%= form.label :industry, "Industry", :class => "uk-form-label" %>
                  <div class="uk-form-controls">
                    <%= form.select :industry, StaticData[:industries].map {|v| [v, v]}, {}, { class: "uk-select" } %>
                  </div>
                </div>

                <div class="uk-margin">
                  <%= form.label :description, "About", :class => "uk-form-label" %>
                  <%= form.hidden_field :description, required: true, id: 'description' %>
                  <div class="uk-form-controls">
                    <trix-editor input="description"></trix-editor>
                  </div>
                </div>

                <div class="uk-margin">
                  <%= form.label :website, "Website", :class => "uk-form-label" %>
                  <div class="uk-form-controls">
                    <%= form.url_field :website, :class => "uk-input" %>
                  </div>
                </div>

                <div class="uk-margin">
                  <%= form.label :email, "Contact Email", :class => "uk-form-label" %>
                  <div class="uk-form-controls">
                    <%= form.email_field :email, required: true, :class => "uk-input" %>
                  </div>
                </div>

                <div class="uk-margin">
                  <%= form.label :phone, "Contact Phone", :class => "uk-form-label" %>
                  <div class="uk-form-controls">
                    <%= form.telephone_field :phone, required: true, :class => "uk-input" %>
                  </div>
                </div>

                <div class="uk-margin">
                  <%= form.label :city, "City", :class => "uk-form-label" %>
                  <div class="uk-form-controls">
                    <%= form.text_field :city, require: true, :class => "uk-input" %>
                  </div>
                </div>

                <div class="uk-margin">
                  <%= form.label :state_or_region, "State/Region", :class => "uk-form-label" %>
                  <div class="uk-form-controls">
                    <%= form.text_field :state_or_region, require: true, :class => "uk-input" %>
                  </div>
                </div>

                <div class="uk-margin">
                  <%= form.label :post_code, "Post/Zip Code", :class => "uk-form-label" %>
                  <div class="uk-form-controls">
                    <%= form.text_field :post_code, require: true, :class => "uk-input" %>
                  </div>
                </div>

                <div class="uk-margin">
                  <%= form.label :country, "Country", :class => "uk-form-label" %>
                  <div class="uk-form-controls">
                    <%= form.select :country, StaticData[:countries].map {|v| [v[:name], v[:code]]}, {}, { class: "uk-select" } %>
                  </div>
                </div>

                <div class="uk-form-controls uk-padding-small uk-padding-remove-left">
                  <div class="uk-margin">
                    <%= form.submit "Register", :class => "uk-button uk-button-primary" %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>

          <div class="uk-flex-first uk-flex-last@m uk-text-left@m uk-width-1-4@m">
            <div class="uk-card uk-card-default uk-card-body uk-margin-bottom dc-content-container">
              <h3>Instructions</h3>
              <p>In order to post jobs, you should register your company. You're allowed to register more than one company which means recruiters can register as many clients as they want.</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  </article>
</main>

app/views/companies/show.html.erb
<% content_for :title do %>
  <%= "#{@company.name} | #{t('app.name')}" %>
<% end %>
<main class="dc-home">
  <article>
    <section class="dc-page--header">
      <div class="uk-container">
        <div class="uk-grid">
          <div class="uk-width-1-2@m uk-margin-small-bottom">
            <h1 class="page--title"><%= link_to @company.name, @company.website %></h1>
          </div>
          <div class="uk-width-1-2@m">
            <p class="dc-job-meta uk-text-right@m">
              <span class="dc-job-type uk-margin-right"><%= @company.industry %></span>
              <%= link_to "Visit Company Website", @company.website %>
            </p>
          </div>
        </div>
      </div>
    </section>

    <section class="dc-main--content">
      <div class="uk-container">
        <div class="uk-grid" >
          <div class="uk-flex-last uk-flex-first@m uk-width-expand@m">
            <div class="uk-card uk-card-default uk-card-body dc-content-container">
              <% if @company.jobs.empty? %>
                <p>No jobs have been posted for <%= @company.name %> yet.</p>
                <% if current_user && current_user.companies.include?(@company)%>
                  <p>Are you hiring for any role? Use this <%= link_to "link", new_job_path %> to create the job post.</p>
                <% end %>
              <% else %>
                <h3>Jobs</h3>
                <%= render 'company_jobs_list', company: @company %>
              <% end %>
            </div>


          </div>

          <div class="uk-flex-first uk-flex-last@m uk-text-left uk-width-1-3@m">
            <div class="uk-card uk-card-default uk-card-body uk-margin-bottom dc-content-container">
              <h2>About Company</h2>
              <p><%= @company.description.html_safe %></p>
              <section class="address">
                <h3>Address</h3>
                <p>
                  <%= @company.city %><br>
                  <%= @company.state_or_region %><br>
                  <%= @company.country %> <%= @company.post_code %>
                </p>
              </section>

              <% if current_user && current_user.companies.include?(@company) %>
                <%= link_to "Edit", edit_company_path(@company), :class => "uk-button uk-button-default", style: "width: 100%" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </section>
  </article>
</main>