config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'pages/terms'
  get 'pages/updates'
  root to: 'pages#index'

  get 'about'   => 'pages#about'
  get 'help'    => 'pages#help'
  get 'pricing' => 'pages#pricing'
  get 'privacy' => 'pages#privacy'
  get 'terms'   => 'pages#terms'
  get 'updates' => 'pages#updates'

  get 'profile' => 'profile#show'

  resources :companies
  resources :jobs do
    collection do
      get 'search'
    end

    member do
      post 'filled'
      post 'vacant'
      post 'renew'
    end
  end

  devise_for :users, skip: %i[sessions registrations passwords]

  devise_scope :user do
    # sessions
    get    'login',  to: 'users/sessions#new', as: :new_user_session
    post   'login',  to: 'users/sessions#login', as: :user_session
    get    'sign_in', to: 'users/sessions#create', as: :start_user_session
    delete 'logout', to: 'users/sessions#destroy', as: :destroy_user_session

    # registrations
    put    '/account',  to: 'users/registrations#update'
    delete '/account',  to: 'users/registrations#destroy'
    post   '/account',  to: 'users/registrations#create'
    get    '/register', to: 'users/registrations#new',    as: :new_user_registration
    get    '/account',  to: 'users/registrations#edit',   as: :edit_user_registration
    patch  '/account',  to: 'users/registrations#update', as: :user_registration
    get    '/account/cancel', to: 'users/registrations#cancel', as: :cancel_user_registration

    # # passwords
    # get   'new-pass',  to: 'users/passwords#new',    as: :new_user_password
    # get   'edit-pass', to: 'users/passwords#edit',   as: :edit_user_password
    # patch 'edit-pass', to: 'users/passwords#update', as: :update_user_password
    # post  'new-pass',  to: 'users/passwords#create', as: :user_password
  end
end

app/views/layouts/_footer.html.erb
<footer>
	<!-- <div class="newsletter-sub">
		<h3>Can't find the jobs you're looking for?</h3>
		<p>Sign up below and we'll send you regular job updates from here.</p>
		<div id="mc_embed_signup">
			<form action="https://devcongress.us19.list-manage.com/subscribe/post?u=e5a8df0953f6615394de1220d&amp;id=04270df5d6" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
			    <div id="mc_embed_signup_scroll">
				<h2></h2>
			<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
			<div class="mc-field-group">
				<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
			</label>
				<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
			</div>
				<div id="mce-responses" class="clear">
					<div class="response" id="mce-error-response" style="display:none"></div>
					<div class="response" id="mce-success-response" style="display:none"></div>
				</div>
			    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_e5a8df0953f6615394de1220d_04270df5d6" tabindex="-1" value=""></div>
			    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
			    </div>
			</form>
		</div>
	</div> -->
	<article>
		<section class="dc-network">
			<div class="uk-container">
				<div class="uk-grid">
					<div class="uk-width-1-2@m">
						<h2 class="dc-network--header">More dev:congress platforms</h2>
					</div>
					<div class="uk-width-1-2@m">
						<nav class="dc-network--nav">
							<a href="https://events.devcongress.org/">Events</a>
							<a href="https://exchange.devcongress.org/">eXchange</a>
							<a href="https://forum.devcongress.org/">Forum</a>
							<a href="https://gharage.com/">gharage</a>
						</nav>
					</div>
				</div>
			</div>
		</section>
		<section class="dc-footer">
			<div class="uk-container">
				<div class="uk-grid">
					<div class="uk-width-auto">
						<%= link_to image_tag('devcongress.svg'), t('app.author_website')   %>
					</div>
					<div class="uk-width-expand">
						<nav class="dc-footer--nav">
							<%= link_to 'Terms', terms_path %>
							<%= link_to 'Privacy', privacy_path %>
							<%= link_to 'Pricing', pricing_path %>
							<%= link_to 'Help', help_path %>
							<%= link_to 'About', about_path %>
							<%= link_to 'Updates', updates_path %>
						</nav>
					</div>
					<div class="uk-width-1 uk-margin-top">
						<p>&copy; <%= Date.today.year %> All rights reserved</p>
					</div>
				</div>
			</div>
		</section>
	</article>
</footer>

app/views/layouts/_header.html.erb
<header class="dc-header">
  <div class="uk-container uk-navbar-container uk-navbar uk-navbar-transparent uk-padding-small uk-padding-remove-top uk-padding-remove-horizontal">
    <div class="uk-navbar-left">
      <%= link_to image_tag( 'devcongress-logo.png', alt: 'devcongress logo', height: '', width: '', class: 'dc-logo' ), root_path, :class => "" %>
    </div>
    <div class="uk-navbar-right">
        <nav class="dc-header--nav">
          <% if user_signed_in? %>
            <%= link_to 'Your Profile', profile_path, class: "dc-header--nav-link" %>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "dc-header--nav-link" %>
          <% else %>
            <%= link_to 'Sign In', new_user_session_path, class: "dc-header--nav-link" %>
            <%= link_to 'Sign Up', new_user_registration_path, class: "dc-header--nav-link" %>
          <% end %>
          <%= link_to '+ Post a Job', new_job_path, class: "uk-button uk-button-primary dc-header--nav-button" %>
        </nav>
    </div>
  </div>
  <%= render 'layouts/notice'	%>
</header>

app/views/layouts/_meta_and_styles.html.erb
<title>
  <%= yield(:title) %>
</title>
<meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<%= favicon_link_tag asset_path('devcongress-logo-32.ico'), :rel => "shortcut icon", :type => "image/x-icon"  %>
<%= favicon_link_tag asset_path('devcongress-logo-57.ico'), :rel => "apple-touch-icon", :sizes => "57x57" %>
<%= favicon_link_tag asset_path('devcongress-logo-72.ico'), :rel => "apple-touch-icon", :sizes => "72x72" %>
<%= favicon_link_tag asset_path('devcongress-logo-114.ico'), :rel => "apple-touch-icon", :sizes => "114x114" %>
<%= favicon_link_tag asset_path('devcongress-logo-144.ico'), :rel => "apple-touch-icon", :sizes => "144x144" %>
<meta name="description" content="<%= t('app.description') -%>" />
<meta name="keywords" content="devcongress, jobs, remote jobs, developer jobs, software, developer, engineer, devcongress jobs, africa software jobs, remote jobs in africa, designer remote, engineer remote" />
<meta name="google-site-verification" content="z9ECY2G8PZ46qx5_5dFZ_a1BHNz9_2v3lZ55QTegnLg" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="referrer" content="always" />
<meta name="theme-color" content="#e6f7fd"/>
<link href="https://fonts.googleapis.com/css?family=Cairo" rel="stylesheet">
<!-- <link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css"> -->

<%# Open Graph %>
<meta name="title" content="<%# yield(:title) %>" />
<meta property="og:type" content="website">
<meta property="og:url" content="<%= request.original_url %>"/>
<meta property="og:title" content="<%# yield(:title) %>" />
<meta property="og:description" content="<%= t('app.description') -%>" />
<meta property="og:image" content="<%= asset_path('devcongress-jobs-meta.jpg') %>" />
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="<%= request.original_url %>"/>
<meta property="twitter:title" content="<%# yield(:title) %>" />
<meta property="twitter:description" content="<%= t('app.description') -%>" />
<meta property="twitter:image" content="<%= asset_path('devcongress-jobs-meta.jpg') %>" />

<%# Report only data from jobs.devcongress.org, since there are many dev/staging hits %>
<% if Rails.env == "production" %>
  <script>  
    (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-KHKSCXW');
  </script>
<% end %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

app/views/layouts/_notice.html.erb
<% if notice %>
  <div class="uk-alert notice">
    <%= notice %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<html>
  <head>
    <%= render 'layouts/meta_and_styles' %>
  </head>
  <body>
    <noscript>
      <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-KHKSCXW" style="display:none;visibility:hidden" width="0"></iframe>
    </noscript>
    <div class="dc-jobs">
      <%= render 'layouts/header'	%>
      <%= yield	 %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>